
def get_columns(_type):
    string_columns = ["MSZoning","Street","Alley","LotShape","LandContour","Utilities","LotConfig","LandSlope","Condition1","Condition2","BldgType","HouseStyle","RoofStyle","RoofMatl","Exterior1st","Exterior2nd","MasVnrType","ExterQual","ExterCond","Foundation","BsmtQual","BsmtCond","BsmtExposure","BsmtFinType1","BsmtFinType2","Heating","HeatingQC","CentralAir","Electrical","KitchenQual","Functional","FireplaceQu","GarageType","GarageFinish","GarageQual","GarageCond","PavedDrive","PoolQC","Fence","MiscFeature","SaleType","SaleCondition","Neighborhood"]
    numcat_columns  = {
            "MSSubClass":16,
            "OverallQual":10,
            "OverallCond":10}
# the below dict is created powered by Microsoft Excel
# I copied the "data_decsrition" text into excel and excelled it's formattation
    categorical_attribs = {
            "MSSubClass":[20,30,40,45,50,60,70,75,80,85,90,120,150,160,180,190,],
            "MSZoning":["A","C","FV","I","RH","RL","RP","RM","C (all)","missing"],
            "Street":["Grvl","Pave","missing"],
            "Alley":["Grvl","Pave","NA","missing"],
            "LotShape":["Reg","IR1","IR2","IR3","missing"],
            "LandContour":["Lvl","Bnk","HLS","Low","missing"],
            "Utilities":["AllPub","NoSewr","NoSeWa","ELO","missing"],
            "LotConfig":["Inside","Corner","CulDSac","FR2","FR3","missing"],
            "LandSlope":["Gtl","Mod","Sev","missing"],
            "Neighborhood":["Blmngtn","Blueste","BrDale","BrkSide","ClearCr","CollgCr","Crawfor","Edwards","Gilbert","IDOTRR","MeadowV","Mitchel","Names","NoRidge","NPkVill","NridgHt","NWAmes","OldTown","SWISU","Sawyer","SawyerW","Somerst","StoneBr","Timber","Veenker","missing"],
            "Condition1":["Artery","Feedr","Norm","RRNn","RRAn","PosN","PosA","RRNe","RRAe","missing"],
            "Condition2":["Artery","Feedr","Norm","RRNn","RRAn","PosN","PosA","RRNe","RRAe","missing"],
            "BldgType":["1Fam","2FmCon","Duplex","TwnhsE","TwnhsI","missing"],
            "HouseStyle":["1Story","1.5Fin","1.5Unf","2Story","2.5Fin","2.5Unf","SFoyer","SLvl","missing"],
            "OverallQual":[10,9,8,7,6,5,4,3,2,1,],
            "OverallCond":[10,9,8,7,6,5,4,3,2,1,],
            "RoofStyle":["Flat","Gable","Gambrel","Hip","Mansard","Shed","missing"],
            "RoofMatl":["ClyTile","CompShg","Membran","Metal","Roll","Tar&Grv","WdShake","WdShngl","missing"],
            "Exterior1st":["AsbShng","AsphShn","BrkComm","BrkFace","CBlock","CemntBd","HdBoard","ImStucc","MetalSd","Other","Plywood","PreCast","Stone","Stucco","VinylSd","Wd Sdng","WdShing","missing"],
            "Exterior2nd":["AsbShng","AsphShn","BrkComm","BrkFace","CBlock","CemntBd","HdBoard","ImStucc","MetalSd","Other","Plywood","PreCast","Stone","Stucco","VinylSd","Wd Sdng","WdShing","missing"],
            "MasVnrType":["BrkCmn","BrkFace","CBlock","None","Stone","","missing"],
            "ExterQual":["Ex","Gd","TA","Fa","Po","missing"],
            "ExterCond":["Ex","Gd","TA","Fa","Po","missing"],
            "Foundation":["BrkTil","CBlock","PConc","Slab","Stone","Wood","missing"],
            "BsmtQual":["Ex","Gd","TA","Fa","Po","NA","missing"],
            "BsmtCond":["Ex","Gd","TA","Fa","Po","NA","missing"],
            "BsmtExposure":["Gd","Av","Mn","No","NA","missing"],
            "BsmtFinType1":["GLQ","ALQ","BLQ","Rec","LwQ","Unf","NA","missing"],
            "BsmtFinType2":["GLQ","ALQ","BLQ","Rec","LwQ","Unf","NA","missing"],
            "Heating":["Floor","GasA","GasW","Grav","OthW","Wall","missing"],
            "HeatingQC":["Ex","Gd","TA","Fa","Po","missing"],
            "CentralAir":["N","Y","missing"],
            "Electrical":["SBrkr","FuseA","FuseF","FuseP","Mix","missing"],
            "KitchenQual":["Ex","Gd","TA","Fa","Po","missing"],
            "Functional":["Typ","Min1","Min2","Mod","Maj1","Maj2","Sev","Sal","missing"],
            "FireplaceQu":["Ex","Gd","TA","Fa","Po","NA","missing"],
            "GarageType":["2Types","Attchd","Basment","BuiltIn","CarPort","Detchd","NA","missing"],
            "GarageFinish":["Fin","RFn","Unf","NA","missing"],
            "GarageQual":["Ex","Gd","TA","Fa","Po","NA","missing"],
            "GarageCond":["Ex","Gd","TA","Fa","Po","NA","missing"],
            "PavedDrive":["Y","P","N","missing"],
            "PoolQC":["Ex","Gd","TA","Fa","NA","missing"],
            "Fence":["GdPrv","MnPrv","GdWo","MnWw","NA","missing"],
            "MiscFeature":["Elev","Gar2","Othr","Shed","TenC","NA","missing"],
            "SaleType":["WD","CWD","VWD","New","COD","Con","ConLw","ConLI","ConLD","Oth","missing"],
            "SaleCondition":["Normal","Abnorml","AdjLand","Alloca","Family","Partial","missing"]}
    numerical_columns = [
            "LotFrontage",
            "LotArea",
            "YearBuilt",
            "YearRemodAdd",
            "MasVnrArea",
            "BsmtFinSF1",
            "BsmtFinSF2",
            "BsmtUnfSF",
            "TotalBsmtSF",
            "1stFlrSF",
            "2ndFlrSF",
            "LowQualFinSF",
            "GrLivArea",
            "BsmtFullBath",
            "BsmtHalfBath",
            "FullBath",
            "HalfBath",
            "BedroomAbvGr",
            "KitchenAbvGr",
            "TotRmsAbvGrd",
            "Fireplaces",
            "GarageYrBlt",
            "GarageCars",
            "GarageArea",
            "WoodDeckSF",
            "OpenPorchSF",
            "EnclosedPorch",
            "3SsnPorch",
            "ScreenPorch",
            "PoolArea",
            "MiscVal",
            "MoSold",
            "YrSold"]
    if _type == 'str':
        return string_columns
    elif _type == 'nmc':
        return numcat_columns
    elif _type == 'cat':
        return categorical_attribs
    if _type == 'num':
        return numerical_columns
    
# this is that list we previewslty talked about, "spec_attribs_orders"
the_spec_attribs_orders = {
    "LotShape" : ["Reg","IR1", "IR2", "IR3"],
    "LandContour" : ["Lvl", "Bnk" , "HLS", "Low"],
    "Utilities" : ["AllPub", "NoSewr", "NoSeWa", "ELO"],
    "BldgType" : ["1Fam","2FmCon","Duplx","TwnhsE","TwnhsI"],
    "HouseStyle" : ["1Story","1.5Fin","1.5Unf", "2Story", "2.5Fin", "2.5Unf", "SFoyer", "SLvl"],
    "Street" : ["Grvl","Pave"],
    "Alley" : ["Grvl","Pave","NA"],
    "LotConfig" : ["Inside","Corner","CulDSac","FR2","FR3"],
    "LandSlope" : ["Gtl","Mod","Sev"],
    "ExterQual" : ["Ex","Gd","TA","Fa","Po"],
    "ExterCond" : ["Ex","Gd","TA","Fa","Po"],
    "BsmtCond" : ["Ex","Gd","TA","Fa","Po","NA"],
    "BsmtExposure" : ["Gd","Av","Mn","No","NA"],
    "BsmtFinType1" : ["GLQ","ALQ","BLQ","Rec","LwQ","Unf","NA"],
    "BsmtFinType2" : ["GLQ","ALQ","BLQ","Rec","LwQ","Unf","NA"],
    "HeatingQC" : ["Ex","Gd","TA","Fa","Po"],
    "CentralAir" : ["N","Y"],
    "Electrical" : ["SBrkr","FuseA","FuseF","FuseP","Mix"],
    "KitchenQual" : ["Ex","Gd","TA","Fa","Po"],
    "FireplaceQu" : ["Ex","Gd","TA","Fa","Po","NA"],
    "GarageFinish" : ["Fin","RFn","Unf","NA"],
    "GarageQual" : ["Ex","Gd","TA","Fa","Po","NA"],
    "GarageCond" : ["Ex","Gd","TA","Fa","Po", "NA"],
    "PavedDrive" : ["Y","P","N"],
    "PoolQC" : ["Ex","Gd","TA","Fa","NA"],
    "Fence" : ["GdPrv","MnPrv","GdWo","MnWw","NA"]}